config/routes.rb
Rails.application.routes.draw do
  root 'stories#index', as: :stories_index

  get 'about', to: 'static_pages#about'

  get  'register', to: 'users#new'
  post 'register', to: 'users#create'

  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get  'stories/new'   , to: 'stories#new'   , as: :new_story
  post 'stories/create', to: 'stories#create', as: :create_story
  get  'stories/:id'   , to: 'stories#show'  , as: :show_story

  get    'paragraphs/:id/continue'   , to: 'paragraphs#new'        , as: :new_paragraph
  post   'paragraphs/:id/create'     , to: 'paragraphs#create'     , as: :create_paragraph
  put    'paragraphs/:id/cancel-new' , to: 'paragraphs#cancel_new' , as: :cancel_new_paragraph
  delete 'paragraphs/:id/delete'     , to: 'paragraphs#destroy'    , as: :delete_paragraph
  post   'paragraphs/:id/like'       , to: 'paragraphs#like'       , as: :like_paragraph
  post   'paragraphs/:id/dislike'    , to: 'paragraphs#dislike'    , as: :dislike_paragraph
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% unless type.end_with?("_lower") %>
    <%= render 'shared/flash_single', type: type, message: message %>
  <% end %>
<% end %>

app/views/shared/_flash_lower.html.erb
<% flash.each do |type, message| %>
  <% if type.end_with?("_lower") %>
    <%= render 'shared/flash_single', type: type, message: message %>
  <% end %>
<% end %>

app/views/shared/_flash_single.html.erb
<% alert_name = { notice: "primary",
                  success: "success",
                  alert: "danger",
                  alert_lower: "danger" }[type.to_sym] %>
<div class="alert alert-<%= alert_name %> margin-top-small">
  <%= message %>
</div>

app/views/shared/_footer.html.erb
<div id="footer" class="paper container-lg margin-bottom-none">
  <small>
    <a href="https://github.com/fpsvogel/storytoss">GitHub repo</a>. -
    Made by <a href="https://fpsvogel.com/">Felipe Vogel</a>. -
    Powered by <a href="https://rubyonrails.org/">Ruby on Rails</a> and <a href="https://www.getpapercss.com/">PaperCSS</a>.
  </small>
</div>

app/views/shared/_form_errors.html.erb
<% if form&.object&.errors&.any? %>
  <% form.object.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_meta.html.erb
<title>Story Toss</title>
<meta name="description" content="Write a story with other people bit by bit, and see where it ends up!" />
<link rel="canonical" href="https://storytoss.herokuapp.com/" />

<meta property="og:title" content="Story Toss: Write stories together" />
<meta property="og:description" content="Write a story with other people bit by bit, and see where it ends up!" />
<meta property="og:url" content="https://storytoss.herokuapp.com/" />
<meta property="og:image" content="https://storytoss.herokuapp.com/android-chrome-512x512.png" />
<meta property="og:type" content="website" />

<meta name="twitter:card" content="summary" />
<meta property="twitter:image" content="https://storytoss.herokuapp.com/android-chrome-512x512.png" />
<meta property="twitter:title" content="Story Toss: Write stories together" />
<meta property="twitter:description" content="Write a story with other people bit by bit, and see where it ends up!" />
<meta name="twitter:creator" content="@fpsvogel" />

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-brand">
    <h3><a href="<%= stories_index_path %>">Story Toss</a></h3>
  </div>
  <div class="collapsible">
    <input id="collapsible2" type="checkbox" name="collapsible2">
    <label for="collapsible2">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
    </label>
    <div class="collapsible-body">
      <ul class="inline">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, "data-turbo-method": :delete %></li>
        <% else %>
          <li><%= link_to "Register", register_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div>
  </div>
</nav>