config/routes.rb
Rails.application.routes.draw do
  root 'stories#index', as: :stories_index

  get 'about', to: 'static_pages#about'

  get  'register', to: 'users#new'
  post 'register', to: 'users#create'

  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get  'stories/new'   , to: 'stories#new'   , as: :new_story
  post 'stories/create', to: 'stories#create', as: :create_story
  get  'stories/:id'   , to: 'stories#show'  , as: :show_story

  get    'paragraphs/:id/continue'   , to: 'paragraphs#new'        , as: :new_paragraph
  post   'paragraphs/:id/create'     , to: 'paragraphs#create'     , as: :create_paragraph
  put    'paragraphs/:id/cancel-new' , to: 'paragraphs#cancel_new' , as: :cancel_new_paragraph
  delete 'paragraphs/:id/delete'     , to: 'paragraphs#destroy'    , as: :delete_paragraph
  post   'paragraphs/:id/like'       , to: 'paragraphs#like'       , as: :like_paragraph
  post   'paragraphs/:id/dislike'    , to: 'paragraphs#dislike'    , as: :dislike_paragraph
end

app/models/story.rb
class Story < ApplicationRecord
  include Scorable

  ADDRESS_SEPARATOR = "."
  TITLE_LENGTH = 5

  has_many :paragraphs, dependent: :destroy

  def self.start(content:, author:)
    story = create
    story.paragraphs.create(content: content, author: author, address: "0")
    story
  end

  def first_paragraph
    paragraphs.first
  end

  def paragraph_at(address)
    return first_paragraph if address == "0"
    paragraph_ids = address.split(ADDRESS_SEPARATOR)
    current_paragraph = first_paragraph
    paragraph_ids.each do |paragraph_id|
      current_paragraph = current_paragraph.next_paragraphs.find(paragraph_id)
    end
    current_paragraph
  end

  def progress
    decimal = paragraphs.maximum("level").to_f / Paragraph::MAX_LEVEL
    (decimal * 100).round
  end

  def last_updated_date
    paragraphs.maximum("updated_at").strftime('%F')
  end

  def title
    words = first_paragraph.to_s.split(" ")
    "#{words.slice(0..TITLE_LENGTH - 1).join(" ")}#{" …" if words.count > TITLE_LENGTH}"
  end

  def score
    paragraphs.sum("score")
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]

  def index
    @stories = Story.all
  end

  def show
    story = Story.find(params[:id])
    @title = story.title
    @story_id = story.id
    @branch = StoryBranch.new(story: story,
                              address: params[:branch],
                              user: current_user)
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.start(content: story_params[:content],
                         author: current_user)
    if @story.save
      redirect_to show_story_path(@story), success: "You've started a new story!"
    else
      render :new, status: :see_other
    end
  end

  private

  def story_params
    params.require(:story).permit(:content)
  end
end

app/views/stories/_alternative_preview.html.erb
<a class="link-wrapper" href="/stories/<%= story_id %>?branch=<%= paragraph.address %>#p<%= paragraph.id %>">
  <div class="paper container alternative" style="z-index:<%= 90 - index %>">
    <div class="row margin-bottom-none">
      <span class="alternative-content">
        <%= paragraph %>
      </span>
      <span class="alternative-score <%= paragraph.score_in_a_word %>">
        <%= paragraph.score_formatted %>
      </span>
    </div>
  </div>
</a>

app/views/stories/_new_paragraph_form.html.erb
<%= form_with model: @new_paragraph, url: create_paragraph_path(previous_paragraph), class: "add-paragraph" do |f| %>
  <%= render "shared/form_errors", form: f %>

  <%= f.label :content, "Continue the story:" %>
  <%= f.text_area :content, autofocus: true %>

  <%= f.submit "Save", class: "paper-btn", "data-turbo-frame": "_top" %>
  <%= link_to "Cancel", cancel_new_paragraph_path(previous_paragraph), class: "paper-btn", "data-turbo-method": :put %>
<% end %>

app/views/stories/_new_story_button.html.erb
<%= link_to text, new_story_path, class: "paper-btn #{"margin-top-large" if margin_top}" %>

app/views/stories/_paragraph.html.erb
<%= turbo_frame_tag "p#{paragraph.id}" do %>
  <div class="paper container margin-top story-card" tabindex="-1" data-story-target="card" data-action="click@document->story#unhighlightSelectedParagraph">
    <div class="card-body">
      <div class="row margin-bottom-none">
        <div class="card-text story-body">
          <span class="story-level">
            <%= paragraph.level %>.
          </span>
          <span class="story-content">
            <%= paragraph %>
          </span>
          <div class="story-footer">
            <span class="story-author-date">
              – <%= paragraph.author.username %> on <%= paragraph.last_updated_date %>
            </span>
            <% if paragraph.last_level? %>
              <span class="story-end">(THE END.)</span>
            <% elsif !create_mode %>
              <%= link_to "Continue from here…", new_paragraph_path(paragraph), class: "story-continue-delete" %>
            <% end %>
            <% if paragraph.author == current_user %>
              <%= link_to "Delete", delete_paragraph_path(paragraph), class: "story-continue-delete", "data-turbo-method": :delete, "data-turbo-frame": "_top" %>
            <% end %>
          </div>
        </div>
        <%= render 'stories/paragraph_stats', paragraph: paragraph, reaction: reaction %>
      </div>
    </div>
  </div>

  <%= render 'shared/flash_lower' %>

  <% if create_mode %>
    <%= render 'stories/new_paragraph_form', previous_paragraph: paragraph %>
  <% end %>
<% end %>

app/views/stories/_paragraph_stats.html.erb
<div class="story-stats">
  <div class="score <%= paragraph.score_in_a_word %>">
    <%= paragraph.score_formatted %>
  </div>
  <div class="like-dislike">
    <%= link_to "👍", like_paragraph_path(paragraph), "data-turbo-method": :post, class: ("selected" if reaction == Reaction::LIKE) -%>
    <%# concat trick: from https://stackoverflow.com/questions/53167613/how-to-trim-leading-whitespace-with-in-erb-templates-in-rails-that-end-up %>
    <% concat link_to "👎", dislike_paragraph_path(paragraph), "data-turbo-method": :post, class: ("selected" if reaction == Reaction::DISLIKE) %>
  </div>
</div>

app/views/stories/_reset_view_button.html.erb
<% if @branch.paragraph_selected? %>
  <%= link_to "Reset view", show_story_path(@story_id), class: "paper-btn #{"margin-top-large" if margin_top}" %>
<% end %>

app/views/stories/_story.html.erb
<div class="row margin-top">
  <a class="story-card-link" href="#">
    <div class="card">
      <div class="card-body">
        <div class="row margin-bottom-none">
          <span class="card-text story-preview"><%= story.first_paragraph %> <span class="card-text story-date">–<%= story.last_updated_date %></span></span>
          <div class="story-stats">
            <div class="progress">
              <div class="bar success w-<%= story.progress %>"></div>
            </div>
            <div class="score <%= story.score_in_a_word %>">
              <%= story.score_formatted %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </a>
</div>

app/views/stories/_story_preview.html.erb
<div class="row margin-top story-card">
  <a class="link-wrapper" href="/stories/<%= story.id %>">
    <div class="card">
      <div class="card-body">
        <div class="row margin-bottom-none">
          <span class="card-text story-body">
            <%= story.first_paragraph %>
            <span class="story-author-date">–<%= story.last_updated_date %></span>
          </span>
          <span class="story-stats">
            <div class="progress">
              <div class="bar success w-<%= story.progress %>"></div>
            </div>
            <div class="score <%= story.score_in_a_word %>">
              <%= story.score_formatted %>
            </div>
          </span>
        </div>
      </div>
    </div>
  </a>
</div>

app/views/stories/index.html.erb
<h3>Pick a story and write your own continuation!</h3>

<%= link_to "Or start a new story", new_story_path, class: "paper-btn margin-bottom-small" %>

<%= render partial: 'story_preview', collection: @stories, as: :story %>

app/views/stories/new.html.erb
<%# provide(:title, "New story") %>

<h1>New story</h1>

<%= form_with model: @story, url: create_story_path, class: "create-story" do |f| %>
  <%= render "shared/form_errors", form: f %>

  <%= f.label :content, "Write the first paragraph (max. #{Paragraph::MAX_LENGTH} characters):" %>
  <%= f.text_area :content, autofocus: true %>

  <%= f.submit "Create", class: "paper-btn" %>
<% end %>

app/views/stories/show.html.erb
<h3><%= @title %></h3>

<%= render 'stories/reset_view_button', margin_top: false %>

<div data-controller="story">
  <% @branch.levels.each_with_index do |paragraphs, level_index| %>
    <%= render 'paragraph', paragraph: paragraphs.first,
                            reaction: @branch.reactions[level_index],
                            create_mode: false %>
    <% paragraphs[1..-1].each_with_index do |alternative, par_index| %>
      <%= render 'alternative_preview', paragraph: alternative,
                                        story_id: @story_id,
                                        index: par_index %>
    <% end %>
  <% end %>
</div>

<%= render 'stories/reset_view_button', margin_top: true %>